name: RaptorChat
author: Raptor4694
main: com.raptor.plugins.chat.RaptorChat
version: 4.0.1
api-version: 1.13
commands:
  nick:
    description: Change your nickname
    usage: /<command> [<nickname>]
    permission: raptorchat.command.nick
  namecolor:
    description: Change your name color in chat
    usage: /<command> <color>
    permission: raptorchat.command.namecolor
  realname:
    description: Get someone's real name from a nickname
    usage: /<command> <nickname>
    permission: raptorchat.command.realname
  chatitem:
    description: Chat a hoverable tooltip of your currently held item
    usage: /<command>
    permission: raptorchat.command.chatitem
  mail:
    description: Read and send mail
    usage: |
      /<command> [list [<page>]]
      OR /<command> read [<number>]
      OR /<command> send <recipient> <subject> <message...>
      OR /<command> send <recipient> "<subject...>" <message...>
      OR /<command> reply <number> <message...> 
    permission: raptorchat.command.mail
  reply:
    description: Reply to the person who last private-messaged you
    usage: /<command> <message...>
    aliases:
    - r
    permission: raptorchat.command.reply
  raptorchat:
    description: Get info or reload the RaptorChat plugin.
    usage: /<command> [reload]
    permission: raptorchat.command.raptorchat
permissions:
  raptorchat.command.*:
    children:
      raptorchat.command.nick: true
      raptorchat.command.namecolor: true
      raptorchat.command.realname: true
      raptorchat.command.chatitem: true
      raptorchat.command.mail: true
      raptorchat.command.reply: true
  raptorchat.command.nick:
    description: Allows you to use /nick
    default: true
  raptorchat.command.nick.others:
    description: Allows you to use /nick on other players
    default: op
  raptorchat.command.namecolor:
    description: Allows you to use /namecolor
    default: true
  raptorchat.command.namecolor.others:
    description: Allows you to use /namecolor on other players
    default: op
  raptorchat.command.realname:
    description: Allows you to use /realname
    default: true
  raptorchat.command.chatitem:
    description: Allows you to use /chatitem
    default: true
  raptorchat.command.reload:
    description: Allows you to use /raptorchat
    default: op
  raptorchat.command.mail:
    description: Allows you to use /mail
    default: true
  raptorchat.command.reply:
    description: Allows you to use /reply
    default: true
